sintomas = [[["dolor"],["leve"]], [["dolor",],["moderadamente"],["intenso"]], [["dolor"],["intenso"]],
            [["dolor"],["insoportable"]],[["retortijones"]],[["dolor"],["colico"]],
            [["dolor"],["punzante"]],[["quemazón"]],[["dolor"],["vago"]],[["dolor"],["comer"]],[["hambre"]],
            [["distensión"]],[["náuseas"]],[["vómitos"]],[["malestar"],["estomacal"]],[["sudoración"]],
            [["taquicardia"]],[["sangre"],["orina"]],[["ardor"],["orina"]],[["dolor"],["orina"]],
            [["sensación","ganas","necesidad"],["imperiosa","imperiosas","constanstes"],["orinar","miccionar","mear"]],
            [["sagre","sangrado"],["heces","excremento","excrementos","oculta"]],
            [["dolor","dolores"],["evacuación","evacuar","evacuacion","excrección","excretar","excrecion","cagar"]],
            [["evacuación","evacuar","evacuacion","excrección","excretar","excrecion"],["incompleta","no completa","inacabada","no acabada"]],
            [["diarrea","descomposición","descomposicion","descompuesto"]],
            [["diarrea","descomposición","descomposicion","descompuesto"],["sangre","sangrado"]],
            [["bulto","protuberancia"],"indolora",["ingle","escroto"]],[["fiebre"]],[["piel amarilla","ictericia"]],
            [["estreñimiento"]],[["pérdida","perder"],["peso"]],[["cansancio","cansado","fatiga","fatigado","agotado","agotamiento"]],
            [["saciado","saciedad"]]]
