sintomas = [[["dolor"],["leve"]],
            [["dolor",],["moderadamente"],["intenso"]],
            [["dolor"],["intenso"]],
            [["dolor"],["insoportable"]],
            [["retortijones","contracciones","contracción","contraccion"]],
            [["dolor"],["colico","cólico"]],
            [["dolor"],["punzante"]],
            [["quemazón"]],
            [["dolor"],["vago"]],
            [["dolor"],["comer"]],
            [["hambre"]],
            [["distensión"]],
            [["náuseas"]],
            [["vómitos","vómito","vomito","vomitar"]],
            [["malestar","molestia"],["estomacal","estómago","estomago"]],
            [["sudoración","sudor"]],
            [["taquicardia","corazón rápido","latido rápido"]],
            [["sangre","sangrado"],["orina","pis","orinar"]],[["ardor"],
            ["orina","pis","orinar"]],
            [["dolor"],["orina","orinar","pis"]],
            [["sensación","ganas","necesidad"],["imperiosa","imperiosas","constanstes"],["orinar","miccionar","mear"]],
            [["sagre","sangrado"],["heces","excremento","excrementos","oculta"]],
            [["dolor","dolores"],["evacuación","evacuar","evacuacion","excrección","excretar","excrecion","cagar"]],
            [["evacuación","evacuar","evacuacion","excrección","excretar","excrecion"],["incompleta","no completa","inacabada","no acabada"]],
            [["diarrea","descomposición","descomposicion","descompuesto"]],
            [["diarrea","descomposición","descomposicion","descompuesto"],["sangre","sangrado"]],
            [["bulto","protuberancia"],"indolora",["ingle","escroto"]],[["fiebre"]],
            [["piel amarilla","ictericia","ojos amarillos","amarillo","amarillentos","amarillenta"]],
            [["estreñimiento"]],
            [["pérdida","perder"],["peso"]],
            [["cansancio","cansado","fatiga","fatigado","agotado","agotamiento"]],
            [["saciado","saciedad"]]]
